version: '3.8'

services:
  hirovo-api:
    image: mstfaock/hirovo-api:latest
    container_name: hirovo-api-container
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=HirovoDb;User=sa;Password=FRAudnxd4rzcVPt;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - hirovo-network

  iam-api:
    image: mstfaock/hirovo-iam-api:latest
    container_name: iam-api-container
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=HirovoDb;User=sa;Password=FRAudnxd4rzcVPt;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - hirovo-network

  api-gateway:
    image: mstfaock/hirovo-api-gateway:latest
    container_name: hirovo-api-gateway
    ports:
      - "5000:8080"
    depends_on:
      - hirovo-api
      - iam-api
    networks:
      - hirovo-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "FRAudnxd4rzcVPt"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - hirovo-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api-gateway
    networks:
      - hirovo-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
  
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins-dotnet
    container_name: jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /maden:/maden
    networks:
      - hirovo-network

volumes:
  certbot-etc:
  certbot-var:
  jenkins_home:

networks:
  hirovo-network:
    driver: bridge
